apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adolfo-d
  namespace: mathieu-argo
spec:
  destination:
  namespace: a2b78
    server: https://kubernetes.default.svc
  project: adolfo
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helmchart
    repoURL: git@github.com:O-clock-Hati/challenge-s15-e06-A2B78.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - Replace=true