apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adolfo-dev
spec:
  destination:
    namespace: a2b78
    server: https://kubernetes.default.svc
  project: adolfo-dev
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helmdev
    repoURL: 'git@github.com:A2B78/helm-argo-dev.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - Replace=true