apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generateName: adolfo-
  namespace: mathieu-argo
spec:
  destination:
    namespace: mathieu-argo
    server: https://kubernetes.default.svc
  project: adolfo-dev
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helmchart-prod
    repoURL: git@github.com:O-clock-Hati/challenge-s15-e06-A2B78.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
    path: helmchart-dev
    repoURL: git@github.com:O-clock-Hati/challenge-s15-e06-A2B78.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - Replace=true
