apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adolfo-dev
spec:
  destination:
    name: in-cluster
    server: 'https://kubernetes.default.svc'
  source:
    path: helmchart
    repoURL: 'git@github.com:O-clock-Hati/challenge-s15-e06-A2B78.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: adolfo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true