apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
  name: adolfo-dev
  namespace: mathieu-argo
spec:
  destination:
    namespace: a2b78
    server: 'https://kubernetes.default.svc'
  project: adolfo-dev
  sources:
    - helm:
        valueFiles:
          - values.yaml
      path: helmchart
      repoURL: 'git@github.com:O-clock-Hati/challenge-s15-e06-A2B78.git'
      targetRevision: HEAD
    - ref: values
      repoURL: 'git@github.com:A2B78/helm-argo-dev.git'
      targetRevision: HEAD
      path: helmdev
  syncPolicy:
    automated: {}